source/accounts/urls.py
from django.urls import path

from accounts.views import RegisterView, UserDetailView, UserChangeView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('change/', UserChangeView.as_view(), name='change'),

]

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('webapp.urls')),
                  path('accounts/', include('accounts.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from django.db import models
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE,
                                verbose_name='Пользователь')
    phone = PhoneNumberField()

    def get_absolute_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.pk})


    def __str__(self):
        return f"{self.user.username} 's Profile"

    class Meta:
        db_table = 'profile'
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

source/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = [ 'username', 'password1', 'password2', 'first_name', 'last_name', 'email']

class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone']

source/accounts/views.py
from django.contrib.auth import get_user_model, login
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import MultipleObjectMixin

from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm
from accounts.models import Profile


class UserChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'
    form_profile_class = ProfileChangeForm

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'profile_form' not in kwargs:
            context['profile_form'] = self.form_profile_class(instance=self.get_object().profile)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.form_profile_class(instance=self.get_object().profile, data=request.POST,
                                               files=request.FILES)
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        return self.render_to_response(self.get_context_data(form=form, profile_form=profile_form))

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.get_object().pk})

class RegisterView(CreateView):
    model = get_user_model()
    form_class = MyUserCreationForm
    template_name = 'user_create.html'

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url

        next_url = self.request.POST.get('next')
        if next_url:
            return next_url

        return reverse('webapp:index')


class UserDetailView(LoginRequiredMixin, DetailView, MultipleObjectMixin):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


    def get_context_data(self, **kwargs):
        ads = self.get_object().author_ad.all()
        return super().get_context_data(object_list=ads, **kwargs)

source/accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>Вход</h1>
    <form action="" method="post" class="w-50 mx-auto">
        {% csrf_token %}
        {% if has_error %}
            <p class="text-danger">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="row mb-3">
            <label for="username" class="col-sm-4 col-form-label">Имя пользователя: </label>
            <div class="col-sm-8">
                <input type="text" name="username" id="username" class="form-control">
            </div>
        </div>
        <div class="row mb-3">
            <label for="password" class="col-sm-4 col-form-label">Пароль: </label>
            <div class="col-sm-8">
                <input type="password" class="form-control" name="password" id="password">
            </div>
        </div>
        <div class="d-flex">
            <button type="submit" class="btn btn-outline-success mx-auto px-5">Войти</button>
        </div>

    </form>

{% endblock %}

source/accounts/templates/user_change.html
{% extends 'base.html' %}
{% block content %}
    <h1>Поменять личные данные</h1>

    <form action="" method="post" enctype="multipart/form-data">
        {% include 'partial/form.html' with fields_only=True %}
        {% include 'partial/form.html' with form=profile_form button_text="Изменить"%}

    </form>
{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}
{% block content %}
    <h1>Регистрация</h1>

    <form action="" method="post">
        {% include 'partial/form.html' with button_text="Зарегистрироваться" %}

    </form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block nav %}
    {% if user_obj.pk == request.user.pk %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:change' %}">Редактировать </a>
    </li>

    {% endif %}
{% endblock %}

{% block content %}
    <h1>Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>

    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Имя пользователя: {{ user_obj.username }}</h5>
                    <p class="card-text">Имя: {{ user_obj.first_name }}</p>
                    <p class="card-text">Фамилия: {{ user_obj.last_name }}</p>
{#                    <p class="card-text">Телефон {{ user_obj.profile.phone :  }}</p>#}
                    <p class="card-text">Почта: {{ user_obj.email }}</p>
                </div>
            </div>
        </div>
    </div>

{% include 'partial/list_partial.html' with ads=object_list %}
{% endblock %}