source/accounts/urls.py
from django.urls import path

from accounts.views import RegisterView, UserDetailView, UserChangeView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('change/', UserChangeView.as_view(), name='change'),

]

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('webapp.urls')),
                  path('accounts/', include('accounts.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views.ads_views import IndexViews, AdDeleteView, AdUpdateView, AdView, AdCreateView, AdList, AdYes, Adn
from webapp.views.coments_views import AdCommentCreateView, CommentDeleteView

app_name = 'webapp'

urlpatterns = [
    path('', IndexViews.as_view(), name='index'),
    path('ad/<int:pk>/', AdView.as_view(), name='ad_view'),
    path('ad/add/', AdCreateView.as_view(), name='ad_add'),
    path('ad/<int:pk>/update', AdUpdateView.as_view(), name='ad_update'),
    path('ad/<int:pk>/delete', AdDeleteView.as_view(), name='ad_delete'),
    path('comment/<int:pk>/delete', CommentDeleteView.as_view(), name='comment_delete'),
    path('ad/<int:pk>/comment/add/', AdCommentCreateView.as_view(), name='ad_comment_add'),
    path('no_moderated/', AdList.as_view(), name="no_moderated"),
    path('moderated/<int:pk>/', AdYes.as_view(), name="yes"),
    path('no_moderated/<int:pk>/', Adn.as_view(), name="no")


]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


STATUS = [('to_modern', 'на модерацию'), ('published', 'опубликовано'), ('rejected', 'отклонено'), ('to_delete', 'на удаление')]


class Ads(models.Model):
    photo = models.ImageField(null=True, blank=True, upload_to='photos', verbose_name='фотография')
    text = models.CharField(max_length=50, null=False, blank=False, verbose_name='заголовок')
    description = models.TextField(max_length=1000, null=True, blank=True, verbose_name='описание')
    author = models.ForeignKey(get_user_model(), null=False, blank=False, on_delete=models.SET_DEFAULT, default=1,
                               related_name='author_ad',
                               verbose_name="Автор объявления")
    category = models.ForeignKey('webapp.Category', max_length=20, null=False, blank=False, on_delete=models.CASCADE,
                                verbose_name="категория")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="price")
    status = models.CharField(max_length=20, null=False, blank=False, choices=STATUS, default=STATUS[0][0],
                                verbose_name="статус")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Время изменения")
    is_moderated = models.BooleanField(default=False, verbose_name='Подтвержден')

    class Meta:
        permissions = [("choice_ads", "Отбирать объявления")]

    def get_absolute_url(self):
        return reverse('webapp:ad_view', kwargs={'pk': self.pk})

    def __str__(self):
        return f'{self.pk}. {self.text}'

class Category(models.Model):
    name = models.CharField(max_length=30, null=False, blank=False, verbose_name='категория')

class Comment(models.Model):
    text = models.TextField(max_length=400, verbose_name='Комментарий')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1, related_name='comments',
                               verbose_name="Автор")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    ad = models.ForeignKey('webapp.Ads', on_delete=models.CASCADE, related_name='comments',
                                verbose_name="объявление")


    def __str__(self):
        return f'{self.pk}. {self.text[:20]}'

source/webapp/forms.py
from django import forms
from django.forms import widgets
from webapp.models import Ads, Comment


class AdForm(forms.ModelForm):
    class Meta:
        model = Ads
        fields = ['photo', 'text', 'description', 'category', 'price']
        widgets = {
            'text': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }
        error_messages = {
            'text': {
                'required': 'Поле должно быть заполнено'
            }
        }




class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']




class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label='Найти',
                             widget=widgets.TextInput(attrs={'class': "form-control w-25"}))

source/webapp/views/ads_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.http import JsonResponse
from django.utils.http import urlencode
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.db.models import Q
from django.views import View
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView

from webapp.models import Ads
from webapp.forms import AdForm, SimpleSearchForm


class IndexViews(ListView):
    template_name = 'ads/index.html'
    context_object_name = 'ads'
    model = Ads
    ordering = ('-created_at')
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']

    def get_queryset(self):
        queryset = Ads.objects.filter(status='published')
        if self.search_value:
            queryset = queryset.filter(Q(text__icontains=self.search_value) | Q(description__icontains=self.search_value)).filter(status='published')
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class AdView(DetailView):
    template_name = 'ads/ad_detail.html'
    model = Ads

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = self.object
        comments = article.comments.order_by('-created_at')
        context['comments'] = comments
        return context




class AdCreateView(LoginRequiredMixin, CreateView):
    template_name = 'ads/ad_create.html'
    model = Ads
    form_class = AdForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class AdUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = "ads/ad_update.html"
    form_class = AdForm
    model = Ads
    context_object_name = 'ad'
    permission_required = 'webapp.change_ad'

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user



class AdDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'ads/ad_confirm_delete.html'
    model = Ads
    success_url = reverse_lazy('webapp:index')

    def has_permission(self):
        return self.get_object().user == self.request.user

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.status = 'to_delete'
        self.object.save()
        return redirect('webapp:index')

class AdYes(PermissionRequiredMixin, View):

    permission_required = 'webapp.choice_ads'

    def get(self, *args, **kwargs):
        ad = get_object_or_404(Ads, pk=self.kwargs.get('pk'))
        ad.status = 'published'
        ad.save()
        data = {
            'data': ad.pk
        }
        response = JsonResponse(data)
        return response


class Adn(PermissionRequiredMixin, View):
    permission_required = 'webapp.choice_ads'

    def get(self, *args, **kwargs):
        ad = get_object_or_404(Ads, pk=self.kwargs.get('pk'))
        ad.status = 'rejected'
        ad.save()
        data = {
            'data': ad.pk
        }
        response = JsonResponse(data)
        return response

class AdList(PermissionRequiredMixin, ListView):
    template_name = 'for_moderator.html'
    context_object_name = 'ads'
    model = Ads
    ordering = ('-created_at',)
    paginate_by = 3
    permission_required = 'webapp.choice_ads'

source/webapp/views/coments_views.py
from django.contrib.auth.mixins import LoginRequiredMixin,  UserPassesTestMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, DeleteView

from webapp.forms import CommentForm
from webapp.models import Comment, Ads


class AdCommentCreateView(LoginRequiredMixin, CreateView):
    template_name = 'comment/create.html'
    model = Comment
    form_class = CommentForm

    def get_success_url(self):
        return reverse('webapp:ad_view', kwargs={'pk': self.object.ad.pk})

    def form_valid(self, form):
        ad = get_object_or_404(Ads, pk=self.kwargs.get('pk'))
        form.instance.ad = ad
        form.instance.author = self.request.user
        return super().form_valid(form)



class CommentDeleteView(UserPassesTestMixin, DeleteView):
    model = Comment

    def test_func(self):
        return self.request.user.has_perm('webapp.delete_comment') or self.get_object().author == self.request.user

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:ad_view', kwargs={'pk': self.object.ad.pk})

source/webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>{% block title %}Gallery{% endblock %}</title>
</head>
<body class="bg-secondary">
<nav class="navbar navbar-expand-lg navbar-dark  bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'webapp:index' %}">Home</a>
    {% if perms.webapp.delete_ad %}
        <a class="navbar-brand" href="{% url 'webapp:no_moderated' %}">Stuff only</a>
    {% endif %}
    {% if request.user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'webapp:ad_add' %}">Add Ad</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% block nav %}{% endblock %}

            </ul>

            {% if request.user.is_authenticated %}
                    <p class="ms-auto text-secondary d-inline-block my-0 py-auto" >Hi, <a href="{% url 'accounts:detail' request.user.pk %}">{{ request.user.username }}</a></p>
                    <a class="btn btn-dark ms-2" href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Выйти</a>
            {% else %}
                    <a class="btn btn-dark ms-auto" href="{% url 'accounts:login' %}?next={% url 'webapp:index' %}">Log in</a>
                    <a class="btn btn-outline-secondary ms-2" href="{% url 'accounts:create' %}">Регистрация</a>
            {% endif %}
        </div>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>


<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>

<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

source/webapp/templates/for_moderator.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% include 'partial/simple_search.html' %}
        {% for ad in ads %}
            < <div class="col-4 my-3">
                    <div class="card">
                        <div class="card-body">
                            {% if ad.photo %}
                            <img src="{{ ad.photo.url }}" class="img-fluid rounded-start w-75">
                            {% endif %}
                            <h5 class="card-title">{{ ad.title }} </h5>
                             <a href="{% url 'accounts:detail' request.user.pk %} ">Author: {{ ad.author }}</a>
                            <p class="card-text">Цена: {{ ad.price }}</p>
                            <a href="{{ ad.get_absolute_url }}" class="btn btn-primary">Подробнее...</a>
                            <button id="button" class="btn btn-success" data-index-link="{% url 'webapp:yes' ad.pk %}">Одобрить</button>
                            <button id="button" class="btn btn-danger" data-index-link="{% url 'webapp:no' ad.pk %}">Отклонить</button>
                        </div>
                    </div>
                </div>

        {% endfor %}
     {% if is_paginated %}
            {% include 'partial/pagination.html' %}
    {% endif %}


{% endblock %}